import type { Metadata } from 'next'
import {
  Inter,
  Spectral,
  Libre_Baskerville,
  Source_Serif_4,
  JetBrains_Mono,
} from 'next/font/google'
import './globals.scss'
import '@mantine/core/styles.css'
import { createTheme, MantineProvider } from '@mantine/core'
import { ColorSchemeScript } from '@mantine/core'
import { Analytics } from '@vercel/analytics/react'

const inter = Inter({ subsets: ['latin'] })
const spectral = Spectral({ subsets: ['latin'], weight: ['400', '700'] })
const libre = Libre_Baskerville({ subsets: ['latin'], weight: ['400', '700'] })
const jet = JetBrains_Mono({ subsets: ['latin'], weight: ['400', '700'] })
const source = Source_Serif_4({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const theme = createTheme({
  fontFamily: inter.style.fontFamily,
  /** Put your mantine theme override here */
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
        <Analytics />
      </body>
    </html>
  )
}
